use super::bus::Bus;
use super::cpu::Cpu;

#[derive(Copy, Clone)]
pub struct Instruction {
    pub name: &'static str,
    pub addr: fn(&mut Cpu, &mut Bus) -> u8,
    pub operate: fn(&mut Cpu, &mut Bus) -> u8,
    pub mode: AddrMode,
    pub cycles: u8,
}

#[derive(Copy, Clone, PartialEq, Eq)]
pub enum AddrMode {
    Imp,
    Imm,
    Zp0,
    Zpx,
    Zpy,
    Rel,
    Abs,
    Abx,
    Aby,
    Ind,
    Izx,
    Izy,
}

pub fn get_instruction(opcode: u8) -> Instruction {
    let row = (opcode / 16) as usize;
    let col = (opcode % 16) as usize;

    INSTRUCTIONS[row][col]
}

const INSTRUCTIONS: [[Instruction; 16]; 16] = [
    [
        Instruction {
            name: "brk",
            operate: Cpu::brk,
            addr: Cpu::imm,
            mode: AddrMode::Imm,
            cycles: 7,
        },
        Instruction {
            name: "ora",
            operate: Cpu::ora,
            addr: Cpu::izx,
            mode: AddrMode::Izx,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 8,
        },
        Instruction {
            name: "???",
            operate: Cpu::nop,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 3,
        },
        Instruction {
            name: "ora",
            operate: Cpu::ora,
            addr: Cpu::zp0,
            mode: AddrMode::Zp0,
            cycles: 3,
        },
        Instruction {
            name: "asl",
            operate: Cpu::asl,
            addr: Cpu::zp0,
            mode: AddrMode::Zp0,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 5,
        },
        Instruction {
            name: "php",
            operate: Cpu::php,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 3,
        },
        Instruction {
            name: "ora",
            operate: Cpu::ora,
            addr: Cpu::imm,
            mode: AddrMode::Imm,
            cycles: 2,
        },
        Instruction {
            name: "asl",
            operate: Cpu::asl,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: Cpu::nop,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "ora",
            operate: Cpu::ora,
            addr: Cpu::abs,
            mode: AddrMode::Abs,
            cycles: 4,
        },
        Instruction {
            name: "asl",
            operate: Cpu::asl,
            addr: Cpu::abs,
            mode: AddrMode::Abs,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 6,
        },
    ],
    [
        Instruction {
            name: "bpl",
            operate: Cpu::bpl,
            addr: Cpu::rel,
            mode: AddrMode::Rel,
            cycles: 2,
        },
        Instruction {
            name: "ora",
            operate: Cpu::ora,
            addr: Cpu::izy,
            mode: AddrMode::Izy,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 8,
        },
        Instruction {
            name: "???",
            operate: Cpu::nop,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "ora",
            operate: Cpu::ora,
            addr: Cpu::zpx,
            mode: AddrMode::Zpx,
            cycles: 4,
        },
        Instruction {
            name: "asl",
            operate: Cpu::asl,
            addr: Cpu::zpx,
            mode: AddrMode::Zpx,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 6,
        },
        Instruction {
            name: "clc",
            operate: Cpu::clc,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "ora",
            operate: Cpu::ora,
            addr: Cpu::aby,
            mode: AddrMode::Aby,
            cycles: 4,
        },
        Instruction {
            name: "???",
            operate: Cpu::nop,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: Cpu::nop,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "ora",
            operate: Cpu::ora,
            addr: Cpu::abx,
            mode: AddrMode::Abx,
            cycles: 4,
        },
        Instruction {
            name: "asl",
            operate: Cpu::asl,
            addr: Cpu::abx,
            mode: AddrMode::Abx,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 7,
        },
    ],
    [
        Instruction {
            name: "jsr",
            operate: Cpu::jsr,
            addr: Cpu::abs,
            mode: AddrMode::Abs,
            cycles: 6,
        },
        Instruction {
            name: "and",
            operate: Cpu::and,
            addr: Cpu::izx,
            mode: AddrMode::Izx,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 8,
        },
        Instruction {
            name: "bit",
            operate: Cpu::bit,
            addr: Cpu::zp0,
            mode: AddrMode::Zp0,
            cycles: 3,
        },
        Instruction {
            name: "and",
            operate: Cpu::and,
            addr: Cpu::zp0,
            mode: AddrMode::Zp0,
            cycles: 3,
        },
        Instruction {
            name: "rol",
            operate: Cpu::rol,
            addr: Cpu::zp0,
            mode: AddrMode::Zp0,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 5,
        },
        Instruction {
            name: "plp",
            operate: Cpu::plp,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "and",
            operate: Cpu::and,
            addr: Cpu::imm,
            mode: AddrMode::Imm,
            cycles: 2,
        },
        Instruction {
            name: "rol",
            operate: Cpu::rol,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "bit",
            operate: Cpu::bit,
            addr: Cpu::abs,
            mode: AddrMode::Abs,
            cycles: 4,
        },
        Instruction {
            name: "and",
            operate: Cpu::and,
            addr: Cpu::abs,
            mode: AddrMode::Abs,
            cycles: 4,
        },
        Instruction {
            name: "rol",
            operate: Cpu::rol,
            addr: Cpu::abs,
            mode: AddrMode::Abs,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 6,
        },
    ],
    [
        Instruction {
            name: "bmi",
            operate: Cpu::bmi,
            addr: Cpu::rel,
            mode: AddrMode::Rel,
            cycles: 2,
        },
        Instruction {
            name: "and",
            operate: Cpu::and,
            addr: Cpu::izy,
            mode: AddrMode::Izy,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 8,
        },
        Instruction {
            name: "???",
            operate: Cpu::nop,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "and",
            operate: Cpu::and,
            addr: Cpu::zpx,
            mode: AddrMode::Zpx,
            cycles: 4,
        },
        Instruction {
            name: "rol",
            operate: Cpu::rol,
            addr: Cpu::zpx,
            mode: AddrMode::Zpx,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 6,
        },
        Instruction {
            name: "sec",
            operate: Cpu::sec,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "and",
            operate: Cpu::and,
            addr: Cpu::aby,
            mode: AddrMode::Aby,
            cycles: 4,
        },
        Instruction {
            name: "???",
            operate: Cpu::nop,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: Cpu::nop,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "and",
            operate: Cpu::and,
            addr: Cpu::abx,
            mode: AddrMode::Abx,
            cycles: 4,
        },
        Instruction {
            name: "rol",
            operate: Cpu::rol,
            addr: Cpu::abx,
            mode: AddrMode::Abx,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 7,
        },
    ],
    [
        Instruction {
            name: "rti",
            operate: Cpu::rti,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 6,
        },
        Instruction {
            name: "eor",
            operate: Cpu::eor,
            addr: Cpu::izx,
            mode: AddrMode::Izx,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 8,
        },
        Instruction {
            name: "???",
            operate: Cpu::nop,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 3,
        },
        Instruction {
            name: "eor",
            operate: Cpu::eor,
            addr: Cpu::zp0,
            mode: AddrMode::Zp0,
            cycles: 3,
        },
        Instruction {
            name: "lsr",
            operate: Cpu::lsr,
            addr: Cpu::zp0,
            mode: AddrMode::Zp0,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 5,
        },
        Instruction {
            name: "pha",
            operate: Cpu::pha,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 3,
        },
        Instruction {
            name: "eor",
            operate: Cpu::eor,
            addr: Cpu::imm,
            mode: AddrMode::Imm,
            cycles: 2,
        },
        Instruction {
            name: "lsr",
            operate: Cpu::lsr,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "jmp",
            operate: Cpu::jmp,
            addr: Cpu::abs,
            mode: AddrMode::Abs,
            cycles: 3,
        },
        Instruction {
            name: "eor",
            operate: Cpu::eor,
            addr: Cpu::abs,
            mode: AddrMode::Abs,
            cycles: 4,
        },
        Instruction {
            name: "lsr",
            operate: Cpu::lsr,
            addr: Cpu::abs,
            mode: AddrMode::Abs,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 6,
        },
    ],
    [
        Instruction {
            name: "bvc",
            operate: Cpu::bvc,
            addr: Cpu::rel,
            mode: AddrMode::Rel,
            cycles: 2,
        },
        Instruction {
            name: "eor",
            operate: Cpu::eor,
            addr: Cpu::izy,
            mode: AddrMode::Izy,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 8,
        },
        Instruction {
            name: "???",
            operate: Cpu::nop,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "eor",
            operate: Cpu::eor,
            addr: Cpu::zpx,
            mode: AddrMode::Zpx,
            cycles: 4,
        },
        Instruction {
            name: "lsr",
            operate: Cpu::lsr,
            addr: Cpu::zpx,
            mode: AddrMode::Zpx,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 6,
        },
        Instruction {
            name: "cli",
            operate: Cpu::cli,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "eor",
            operate: Cpu::eor,
            addr: Cpu::aby,
            mode: AddrMode::Aby,
            cycles: 4,
        },
        Instruction {
            name: "???",
            operate: Cpu::nop,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: Cpu::nop,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "eor",
            operate: Cpu::eor,
            addr: Cpu::abx,
            mode: AddrMode::Abx,
            cycles: 4,
        },
        Instruction {
            name: "lsr",
            operate: Cpu::lsr,
            addr: Cpu::abx,
            mode: AddrMode::Abx,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 7,
        },
    ],
    [
        Instruction {
            name: "rts",
            operate: Cpu::rts,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 6,
        },
        Instruction {
            name: "adc",
            operate: Cpu::adc,
            addr: Cpu::izx,
            mode: AddrMode::Izx,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 8,
        },
        Instruction {
            name: "???",
            operate: Cpu::nop,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 3,
        },
        Instruction {
            name: "adc",
            operate: Cpu::adc,
            addr: Cpu::zp0,
            mode: AddrMode::Zp0,
            cycles: 3,
        },
        Instruction {
            name: "ror",
            operate: Cpu::ror,
            addr: Cpu::zp0,
            mode: AddrMode::Zp0,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 5,
        },
        Instruction {
            name: "pla",
            operate: Cpu::pla,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "adc",
            operate: Cpu::adc,
            addr: Cpu::imm,
            mode: AddrMode::Imm,
            cycles: 2,
        },
        Instruction {
            name: "ror",
            operate: Cpu::ror,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "jmp",
            operate: Cpu::jmp,
            addr: Cpu::ind,
            mode: AddrMode::Ind,
            cycles: 5,
        },
        Instruction {
            name: "adc",
            operate: Cpu::adc,
            addr: Cpu::abs,
            mode: AddrMode::Abs,
            cycles: 4,
        },
        Instruction {
            name: "ror",
            operate: Cpu::ror,
            addr: Cpu::abs,
            mode: AddrMode::Abs,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 6,
        },
    ],
    [
        Instruction {
            name: "bvs",
            operate: Cpu::bvs,
            addr: Cpu::rel,
            mode: AddrMode::Rel,
            cycles: 2,
        },
        Instruction {
            name: "adc",
            operate: Cpu::adc,
            addr: Cpu::izy,
            mode: AddrMode::Izy,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 8,
        },
        Instruction {
            name: "???",
            operate: Cpu::nop,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "adc",
            operate: Cpu::adc,
            addr: Cpu::zpx,
            mode: AddrMode::Zpx,
            cycles: 4,
        },
        Instruction {
            name: "ror",
            operate: Cpu::ror,
            addr: Cpu::zpx,
            mode: AddrMode::Zpx,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 6,
        },
        Instruction {
            name: "sei",
            operate: Cpu::sei,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "adc",
            operate: Cpu::adc,
            addr: Cpu::aby,
            mode: AddrMode::Aby,
            cycles: 4,
        },
        Instruction {
            name: "???",
            operate: Cpu::nop,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: Cpu::nop,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "adc",
            operate: Cpu::adc,
            addr: Cpu::abx,
            mode: AddrMode::Abx,
            cycles: 4,
        },
        Instruction {
            name: "ror",
            operate: Cpu::ror,
            addr: Cpu::abx,
            mode: AddrMode::Abx,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 7,
        },
    ],
    [
        Instruction {
            name: "???",
            operate: Cpu::nop,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "sta",
            operate: Cpu::sta,
            addr: Cpu::izx,
            mode: AddrMode::Izx,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: Cpu::nop,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 6,
        },
        Instruction {
            name: "sty",
            operate: Cpu::sty,
            addr: Cpu::zp0,
            mode: AddrMode::Zp0,
            cycles: 3,
        },
        Instruction {
            name: "sta",
            operate: Cpu::sta,
            addr: Cpu::zp0,
            mode: AddrMode::Zp0,
            cycles: 3,
        },
        Instruction {
            name: "stx",
            operate: Cpu::stx,
            addr: Cpu::zp0,
            mode: AddrMode::Zp0,
            cycles: 3,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 3,
        },
        Instruction {
            name: "dey",
            operate: Cpu::dey,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: Cpu::nop,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "txa",
            operate: Cpu::txa,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "sty",
            operate: Cpu::sty,
            addr: Cpu::abs,
            mode: AddrMode::Abs,
            cycles: 4,
        },
        Instruction {
            name: "sta",
            operate: Cpu::sta,
            addr: Cpu::abs,
            mode: AddrMode::Abs,
            cycles: 4,
        },
        Instruction {
            name: "stx",
            operate: Cpu::stx,
            addr: Cpu::abs,
            mode: AddrMode::Abs,
            cycles: 4,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
    ],
    [
        Instruction {
            name: "bcc",
            operate: Cpu::bcc,
            addr: Cpu::rel,
            mode: AddrMode::Rel,
            cycles: 2,
        },
        Instruction {
            name: "sta",
            operate: Cpu::sta,
            addr: Cpu::izy,
            mode: AddrMode::Izy,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 6,
        },
        Instruction {
            name: "sty",
            operate: Cpu::sty,
            addr: Cpu::zpx,
            mode: AddrMode::Zpx,
            cycles: 4,
        },
        Instruction {
            name: "sta",
            operate: Cpu::sta,
            addr: Cpu::zpx,
            mode: AddrMode::Zpx,
            cycles: 4,
        },
        Instruction {
            name: "stx",
            operate: Cpu::stx,
            addr: Cpu::zpy,
            mode: AddrMode::Zpy,
            cycles: 4,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "tya",
            operate: Cpu::tya,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "sta",
            operate: Cpu::sta,
            addr: Cpu::aby,
            mode: AddrMode::Aby,
            cycles: 5,
        },
        Instruction {
            name: "txs",
            operate: Cpu::txs,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: Cpu::nop,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 5,
        },
        Instruction {
            name: "sta",
            operate: Cpu::sta,
            addr: Cpu::abx,
            mode: AddrMode::Abx,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 5,
        },
    ],
    [
        Instruction {
            name: "ldy",
            operate: Cpu::ldy,
            addr: Cpu::imm,
            mode: AddrMode::Imm,
            cycles: 2,
        },
        Instruction {
            name: "lda",
            operate: Cpu::lda,
            addr: Cpu::izx,
            mode: AddrMode::Izx,
            cycles: 6,
        },
        Instruction {
            name: "ldx",
            operate: Cpu::ldx,
            addr: Cpu::imm,
            mode: AddrMode::Imm,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 6,
        },
        Instruction {
            name: "ldy",
            operate: Cpu::ldy,
            addr: Cpu::zp0,
            mode: AddrMode::Zp0,
            cycles: 3,
        },
        Instruction {
            name: "lda",
            operate: Cpu::lda,
            addr: Cpu::zp0,
            mode: AddrMode::Zp0,
            cycles: 3,
        },
        Instruction {
            name: "ldx",
            operate: Cpu::ldx,
            addr: Cpu::zp0,
            mode: AddrMode::Zp0,
            cycles: 3,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 3,
        },
        Instruction {
            name: "tay",
            operate: Cpu::tay,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "lda",
            operate: Cpu::lda,
            addr: Cpu::imm,
            mode: AddrMode::Imm,
            cycles: 2,
        },
        Instruction {
            name: "tax",
            operate: Cpu::tax,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "ldy",
            operate: Cpu::ldy,
            addr: Cpu::abs,
            mode: AddrMode::Abs,
            cycles: 4,
        },
        Instruction {
            name: "lda",
            operate: Cpu::lda,
            addr: Cpu::abs,
            mode: AddrMode::Abs,
            cycles: 4,
        },
        Instruction {
            name: "ldx",
            operate: Cpu::ldx,
            addr: Cpu::abs,
            mode: AddrMode::Abs,
            cycles: 4,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
    ],
    [
        Instruction {
            name: "bcs",
            operate: Cpu::bcs,
            addr: Cpu::rel,
            mode: AddrMode::Rel,
            cycles: 2,
        },
        Instruction {
            name: "lda",
            operate: Cpu::lda,
            addr: Cpu::izy,
            mode: AddrMode::Izy,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 5,
        },
        Instruction {
            name: "ldy",
            operate: Cpu::ldy,
            addr: Cpu::zpx,
            mode: AddrMode::Zpx,
            cycles: 4,
        },
        Instruction {
            name: "lda",
            operate: Cpu::lda,
            addr: Cpu::zpx,
            mode: AddrMode::Zpx,
            cycles: 4,
        },
        Instruction {
            name: "ldx",
            operate: Cpu::ldx,
            addr: Cpu::zpy,
            mode: AddrMode::Zpy,
            cycles: 4,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "clv",
            operate: Cpu::clv,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "lda",
            operate: Cpu::lda,
            addr: Cpu::aby,
            mode: AddrMode::Aby,
            cycles: 4,
        },
        Instruction {
            name: "tsx",
            operate: Cpu::tsx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "ldy",
            operate: Cpu::ldy,
            addr: Cpu::abx,
            mode: AddrMode::Abx,
            cycles: 4,
        },
        Instruction {
            name: "lda",
            operate: Cpu::lda,
            addr: Cpu::abx,
            mode: AddrMode::Abx,
            cycles: 4,
        },
        Instruction {
            name: "ldx",
            operate: Cpu::ldx,
            addr: Cpu::aby,
            mode: AddrMode::Aby,
            cycles: 4,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
    ],
    [
        Instruction {
            name: "cpy",
            operate: Cpu::cpy,
            addr: Cpu::imm,
            mode: AddrMode::Imm,
            cycles: 2,
        },
        Instruction {
            name: "cmp",
            operate: Cpu::cmp,
            addr: Cpu::izx,
            mode: AddrMode::Izx,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: Cpu::nop,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 8,
        },
        Instruction {
            name: "cpy",
            operate: Cpu::cpy,
            addr: Cpu::zp0,
            mode: AddrMode::Zp0,
            cycles: 3,
        },
        Instruction {
            name: "cmp",
            operate: Cpu::cmp,
            addr: Cpu::zp0,
            mode: AddrMode::Zp0,
            cycles: 3,
        },
        Instruction {
            name: "dec",
            operate: Cpu::dec,
            addr: Cpu::zp0,
            mode: AddrMode::Zp0,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 5,
        },
        Instruction {
            name: "iny",
            operate: Cpu::iny,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "cmp",
            operate: Cpu::cmp,
            addr: Cpu::imm,
            mode: AddrMode::Imm,
            cycles: 2,
        },
        Instruction {
            name: "dex",
            operate: Cpu::dex,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "cpy",
            operate: Cpu::cpy,
            addr: Cpu::abs,
            mode: AddrMode::Abs,
            cycles: 4,
        },
        Instruction {
            name: "cmp",
            operate: Cpu::cmp,
            addr: Cpu::abs,
            mode: AddrMode::Abs,
            cycles: 4,
        },
        Instruction {
            name: "dec",
            operate: Cpu::dec,
            addr: Cpu::abs,
            mode: AddrMode::Abs,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 6,
        },
    ],
    [
        Instruction {
            name: "bne",
            operate: Cpu::bne,
            addr: Cpu::rel,
            mode: AddrMode::Rel,
            cycles: 2,
        },
        Instruction {
            name: "cmp",
            operate: Cpu::cmp,
            addr: Cpu::izy,
            mode: AddrMode::Izy,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 8,
        },
        Instruction {
            name: "???",
            operate: Cpu::nop,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "cmp",
            operate: Cpu::cmp,
            addr: Cpu::zpx,
            mode: AddrMode::Zpx,
            cycles: 4,
        },
        Instruction {
            name: "dec",
            operate: Cpu::dec,
            addr: Cpu::zpx,
            mode: AddrMode::Zpx,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 6,
        },
        Instruction {
            name: "cld",
            operate: Cpu::cld,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "cmp",
            operate: Cpu::cmp,
            addr: Cpu::aby,
            mode: AddrMode::Aby,
            cycles: 4,
        },
        Instruction {
            name: "nop",
            operate: Cpu::nop,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: Cpu::nop,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "cmp",
            operate: Cpu::cmp,
            addr: Cpu::abx,
            mode: AddrMode::Abx,
            cycles: 4,
        },
        Instruction {
            name: "dec",
            operate: Cpu::dec,
            addr: Cpu::abx,
            mode: AddrMode::Abx,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 7,
        },
    ],
    [
        Instruction {
            name: "cpx",
            operate: Cpu::cpx,
            addr: Cpu::imm,
            mode: AddrMode::Imm,
            cycles: 2,
        },
        Instruction {
            name: "sbc",
            operate: Cpu::sbc,
            addr: Cpu::izx,
            mode: AddrMode::Izx,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: Cpu::nop,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 8,
        },
        Instruction {
            name: "cpx",
            operate: Cpu::cpx,
            addr: Cpu::zp0,
            mode: AddrMode::Zp0,
            cycles: 3,
        },
        Instruction {
            name: "sbc",
            operate: Cpu::sbc,
            addr: Cpu::zp0,
            mode: AddrMode::Zp0,
            cycles: 3,
        },
        Instruction {
            name: "inc",
            operate: Cpu::inc,
            addr: Cpu::zp0,
            mode: AddrMode::Zp0,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 5,
        },
        Instruction {
            name: "inx",
            operate: Cpu::inx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "sbc",
            operate: Cpu::sbc,
            addr: Cpu::imm,
            mode: AddrMode::Imm,
            cycles: 2,
        },
        Instruction {
            name: "nop",
            operate: Cpu::nop,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: Cpu::sbc,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "cpx",
            operate: Cpu::cpx,
            addr: Cpu::abs,
            mode: AddrMode::Abs,
            cycles: 4,
        },
        Instruction {
            name: "sbc",
            operate: Cpu::sbc,
            addr: Cpu::abs,
            mode: AddrMode::Abs,
            cycles: 4,
        },
        Instruction {
            name: "inc",
            operate: Cpu::inc,
            addr: Cpu::abs,
            mode: AddrMode::Abs,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 6,
        },
    ],
    [
        Instruction {
            name: "beq",
            operate: Cpu::beq,
            addr: Cpu::rel,
            mode: AddrMode::Rel,
            cycles: 2,
        },
        Instruction {
            name: "sbc",
            operate: Cpu::sbc,
            addr: Cpu::izy,
            mode: AddrMode::Izy,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 8,
        },
        Instruction {
            name: "???",
            operate: Cpu::nop,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "sbc",
            operate: Cpu::sbc,
            addr: Cpu::zpx,
            mode: AddrMode::Zpx,
            cycles: 4,
        },
        Instruction {
            name: "inc",
            operate: Cpu::inc,
            addr: Cpu::zpx,
            mode: AddrMode::Zpx,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 6,
        },
        Instruction {
            name: "sed",
            operate: Cpu::sed,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "sbc",
            operate: Cpu::sbc,
            addr: Cpu::aby,
            mode: AddrMode::Aby,
            cycles: 4,
        },
        Instruction {
            name: "nop",
            operate: Cpu::nop,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: Cpu::nop,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "sbc",
            operate: Cpu::sbc,
            addr: Cpu::abx,
            mode: AddrMode::Abx,
            cycles: 4,
        },
        Instruction {
            name: "inc",
            operate: Cpu::inc,
            addr: Cpu::abx,
            mode: AddrMode::Abx,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: Cpu::xxx,
            addr: Cpu::imp,
            mode: AddrMode::Imp,
            cycles: 7,
        },
    ],
];
