use super::cpu::CPU;

#[derive(Copy, Clone)]
pub enum AddrMode {
    IMP,
    IMM,
    ZP0,
    ZPX,
    ZPY,
    REL,
    ABS,
    ABX,
    ABY,
    IND,
    IZX,
    IZY,
}

struct Instruction {
    name: &'static str,
    addr: fn(&mut CPU) -> u8,
    operate: fn(&mut CPU) -> u8,
    mode: AddrMode,
    cycles: u8,
}

static INSTRUCTIONS: [[Instruction; 16]; 16] = [
    [
        Instruction {
            name: "BRK",
            operate: CPU::BRK,
            addr: CPU::IMM,
            mode: AddrMode::IMM,
            cycles: 7,
        },
        Instruction {
            name: "ORA",
            operate: CPU::ORA,
            addr: CPU::IZX,
            mode: AddrMode::IZX,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 8,
        },
        Instruction {
            name: "???",
            operate: CPU::NOP,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 3,
        },
        Instruction {
            name: "ORA",
            operate: CPU::ORA,
            addr: CPU::ZP0,
            mode: AddrMode::ZP0,
            cycles: 3,
        },
        Instruction {
            name: "ASL",
            operate: CPU::ASL,
            addr: CPU::ZP0,
            mode: AddrMode::ZP0,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 5,
        },
        Instruction {
            name: "PHP",
            operate: CPU::PHP,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 3,
        },
        Instruction {
            name: "ORA",
            operate: CPU::ORA,
            addr: CPU::IMM,
            mode: AddrMode::IMM,
            cycles: 2,
        },
        Instruction {
            name: "ASL",
            operate: CPU::ASL,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::NOP,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 4,
        },
        Instruction {
            name: "ORA",
            operate: CPU::ORA,
            addr: CPU::ABS,
            mode: AddrMode::ABS,
            cycles: 4,
        },
        Instruction {
            name: "ASL",
            operate: CPU::ASL,
            addr: CPU::ABS,
            mode: AddrMode::ABS,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 6,
        },
    ],
    [
        Instruction {
            name: "BPL",
            operate: CPU::BPL,
            addr: CPU::REL,
            mode: AddrMode::REL,
            cycles: 2,
        },
        Instruction {
            name: "ORA",
            operate: CPU::ORA,
            addr: CPU::IZY,
            mode: AddrMode::IZY,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 8,
        },
        Instruction {
            name: "???",
            operate: CPU::NOP,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 4,
        },
        Instruction {
            name: "ORA",
            operate: CPU::ORA,
            addr: CPU::ZPX,
            mode: AddrMode::ZPX,
            cycles: 4,
        },
        Instruction {
            name: "ASL",
            operate: CPU::ASL,
            addr: CPU::ZPX,
            mode: AddrMode::ZPX,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 6,
        },
        Instruction {
            name: "CLC",
            operate: CPU::CLC,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "ORA",
            operate: CPU::ORA,
            addr: CPU::ABY,
            mode: AddrMode::ABY,
            cycles: 4,
        },
        Instruction {
            name: "???",
            operate: CPU::NOP,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: CPU::NOP,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 4,
        },
        Instruction {
            name: "ORA",
            operate: CPU::ORA,
            addr: CPU::ABX,
            mode: AddrMode::ABX,
            cycles: 4,
        },
        Instruction {
            name: "ASL",
            operate: CPU::ASL,
            addr: CPU::ABX,
            mode: AddrMode::ABX,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 7,
        },
    ],
    [
        Instruction {
            name: "JSR",
            operate: CPU::JSR,
            addr: CPU::ABS,
            mode: AddrMode::ABS,
            cycles: 6,
        },
        Instruction {
            name: "AND",
            operate: CPU::AND,
            addr: CPU::IZX,
            mode: AddrMode::IZX,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 8,
        },
        Instruction {
            name: "BIT",
            operate: CPU::BIT,
            addr: CPU::ZP0,
            mode: AddrMode::ZP0,
            cycles: 3,
        },
        Instruction {
            name: "AND",
            operate: CPU::AND,
            addr: CPU::ZP0,
            mode: AddrMode::ZP0,
            cycles: 3,
        },
        Instruction {
            name: "ROL",
            operate: CPU::ROL,
            addr: CPU::ZP0,
            mode: AddrMode::ZP0,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 5,
        },
        Instruction {
            name: "PLP",
            operate: CPU::PLP,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 4,
        },
        Instruction {
            name: "AND",
            operate: CPU::AND,
            addr: CPU::IMM,
            mode: AddrMode::IMM,
            cycles: 2,
        },
        Instruction {
            name: "ROL",
            operate: CPU::ROL,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "BIT",
            operate: CPU::BIT,
            addr: CPU::ABS,
            mode: AddrMode::ABS,
            cycles: 4,
        },
        Instruction {
            name: "AND",
            operate: CPU::AND,
            addr: CPU::ABS,
            mode: AddrMode::ABS,
            cycles: 4,
        },
        Instruction {
            name: "ROL",
            operate: CPU::ROL,
            addr: CPU::ABS,
            mode: AddrMode::ABS,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 6,
        },
    ],
    [
        Instruction {
            name: "BMI",
            operate: CPU::BMI,
            addr: CPU::REL,
            mode: AddrMode::REL,
            cycles: 2,
        },
        Instruction {
            name: "AND",
            operate: CPU::AND,
            addr: CPU::IZY,
            mode: AddrMode::IZY,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 8,
        },
        Instruction {
            name: "???",
            operate: CPU::NOP,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 4,
        },
        Instruction {
            name: "AND",
            operate: CPU::AND,
            addr: CPU::ZPX,
            mode: AddrMode::ZPX,
            cycles: 4,
        },
        Instruction {
            name: "ROL",
            operate: CPU::ROL,
            addr: CPU::ZPX,
            mode: AddrMode::ZPX,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 6,
        },
        Instruction {
            name: "SEC",
            operate: CPU::SEC,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "AND",
            operate: CPU::AND,
            addr: CPU::ABY,
            mode: AddrMode::ABY,
            cycles: 4,
        },
        Instruction {
            name: "???",
            operate: CPU::NOP,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: CPU::NOP,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 4,
        },
        Instruction {
            name: "AND",
            operate: CPU::AND,
            addr: CPU::ABX,
            mode: AddrMode::ABX,
            cycles: 4,
        },
        Instruction {
            name: "ROL",
            operate: CPU::ROL,
            addr: CPU::ABX,
            mode: AddrMode::ABX,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 7,
        },
    ],
    [
        Instruction {
            name: "RTI",
            operate: CPU::RTI,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 6,
        },
        Instruction {
            name: "EOR",
            operate: CPU::EOR,
            addr: CPU::IZX,
            mode: AddrMode::IZX,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 8,
        },
        Instruction {
            name: "???",
            operate: CPU::NOP,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 3,
        },
        Instruction {
            name: "EOR",
            operate: CPU::EOR,
            addr: CPU::ZP0,
            mode: AddrMode::ZP0,
            cycles: 3,
        },
        Instruction {
            name: "LSR",
            operate: CPU::LSR,
            addr: CPU::ZP0,
            mode: AddrMode::ZP0,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 5,
        },
        Instruction {
            name: "PHA",
            operate: CPU::PHA,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 3,
        },
        Instruction {
            name: "EOR",
            operate: CPU::EOR,
            addr: CPU::IMM,
            mode: AddrMode::IMM,
            cycles: 2,
        },
        Instruction {
            name: "LSR",
            operate: CPU::LSR,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "JMP",
            operate: CPU::JMP,
            addr: CPU::ABS,
            mode: AddrMode::ABS,
            cycles: 3,
        },
        Instruction {
            name: "EOR",
            operate: CPU::EOR,
            addr: CPU::ABS,
            mode: AddrMode::ABS,
            cycles: 4,
        },
        Instruction {
            name: "LSR",
            operate: CPU::LSR,
            addr: CPU::ABS,
            mode: AddrMode::ABS,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 6,
        },
    ],
    [
        Instruction {
            name: "BVC",
            operate: CPU::BVC,
            addr: CPU::REL,
            mode: AddrMode::REL,
            cycles: 2,
        },
        Instruction {
            name: "EOR",
            operate: CPU::EOR,
            addr: CPU::IZY,
            mode: AddrMode::IZY,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 8,
        },
        Instruction {
            name: "???",
            operate: CPU::NOP,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 4,
        },
        Instruction {
            name: "EOR",
            operate: CPU::EOR,
            addr: CPU::ZPX,
            mode: AddrMode::ZPX,
            cycles: 4,
        },
        Instruction {
            name: "LSR",
            operate: CPU::LSR,
            addr: CPU::ZPX,
            mode: AddrMode::ZPX,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 6,
        },
        Instruction {
            name: "CLI",
            operate: CPU::CLI,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "EOR",
            operate: CPU::EOR,
            addr: CPU::ABY,
            mode: AddrMode::ABY,
            cycles: 4,
        },
        Instruction {
            name: "???",
            operate: CPU::NOP,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: CPU::NOP,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 4,
        },
        Instruction {
            name: "EOR",
            operate: CPU::EOR,
            addr: CPU::ABX,
            mode: AddrMode::ABX,
            cycles: 4,
        },
        Instruction {
            name: "LSR",
            operate: CPU::LSR,
            addr: CPU::ABX,
            mode: AddrMode::ABX,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 7,
        },
    ],
    [
        Instruction {
            name: "RTS",
            operate: CPU::RTS,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 6,
        },
        Instruction {
            name: "ADC",
            operate: CPU::ADC,
            addr: CPU::IZX,
            mode: AddrMode::IZX,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 8,
        },
        Instruction {
            name: "???",
            operate: CPU::NOP,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 3,
        },
        Instruction {
            name: "ADC",
            operate: CPU::ADC,
            addr: CPU::ZP0,
            mode: AddrMode::ZP0,
            cycles: 3,
        },
        Instruction {
            name: "ROR",
            operate: CPU::ROR,
            addr: CPU::ZP0,
            mode: AddrMode::ZP0,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 5,
        },
        Instruction {
            name: "PLA",
            operate: CPU::PLA,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 4,
        },
        Instruction {
            name: "ADC",
            operate: CPU::ADC,
            addr: CPU::IMM,
            mode: AddrMode::IMM,
            cycles: 2,
        },
        Instruction {
            name: "ROR",
            operate: CPU::ROR,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "JMP",
            operate: CPU::JMP,
            addr: CPU::IND,
            mode: AddrMode::IND,
            cycles: 5,
        },
        Instruction {
            name: "ADC",
            operate: CPU::ADC,
            addr: CPU::ABS,
            mode: AddrMode::ABS,
            cycles: 4,
        },
        Instruction {
            name: "ROR",
            operate: CPU::ROR,
            addr: CPU::ABS,
            mode: AddrMode::ABS,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 6,
        },
    ],
    [
        Instruction {
            name: "BVS",
            operate: CPU::BVS,
            addr: CPU::REL,
            mode: AddrMode::REL,
            cycles: 2,
        },
        Instruction {
            name: "ADC",
            operate: CPU::ADC,
            addr: CPU::IZY,
            mode: AddrMode::IZY,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 8,
        },
        Instruction {
            name: "???",
            operate: CPU::NOP,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 4,
        },
        Instruction {
            name: "ADC",
            operate: CPU::ADC,
            addr: CPU::ZPX,
            mode: AddrMode::ZPX,
            cycles: 4,
        },
        Instruction {
            name: "ROR",
            operate: CPU::ROR,
            addr: CPU::ZPX,
            mode: AddrMode::ZPX,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 6,
        },
        Instruction {
            name: "SEI",
            operate: CPU::SEI,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "ADC",
            operate: CPU::ADC,
            addr: CPU::ABY,
            mode: AddrMode::ABY,
            cycles: 4,
        },
        Instruction {
            name: "???",
            operate: CPU::NOP,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: CPU::NOP,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 4,
        },
        Instruction {
            name: "ADC",
            operate: CPU::ADC,
            addr: CPU::ABX,
            mode: AddrMode::ABX,
            cycles: 4,
        },
        Instruction {
            name: "ROR",
            operate: CPU::ROR,
            addr: CPU::ABX,
            mode: AddrMode::ABX,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 7,
        },
    ],
    [
        Instruction {
            name: "???",
            operate: CPU::NOP,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "STA",
            operate: CPU::STA,
            addr: CPU::IZX,
            mode: AddrMode::IZX,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::NOP,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 6,
        },
        Instruction {
            name: "STY",
            operate: CPU::STY,
            addr: CPU::ZP0,
            mode: AddrMode::ZP0,
            cycles: 3,
        },
        Instruction {
            name: "STA",
            operate: CPU::STA,
            addr: CPU::ZP0,
            mode: AddrMode::ZP0,
            cycles: 3,
        },
        Instruction {
            name: "STX",
            operate: CPU::STX,
            addr: CPU::ZP0,
            mode: AddrMode::ZP0,
            cycles: 3,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 3,
        },
        Instruction {
            name: "DEY",
            operate: CPU::DEY,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::NOP,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "TXA",
            operate: CPU::TXA,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "STY",
            operate: CPU::STY,
            addr: CPU::ABS,
            mode: AddrMode::ABS,
            cycles: 4,
        },
        Instruction {
            name: "STA",
            operate: CPU::STA,
            addr: CPU::ABS,
            mode: AddrMode::ABS,
            cycles: 4,
        },
        Instruction {
            name: "STX",
            operate: CPU::STX,
            addr: CPU::ABS,
            mode: AddrMode::ABS,
            cycles: 4,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 4,
        },
    ],
    [
        Instruction {
            name: "BCC",
            operate: CPU::BCC,
            addr: CPU::REL,
            mode: AddrMode::REL,
            cycles: 2,
        },
        Instruction {
            name: "STA",
            operate: CPU::STA,
            addr: CPU::IZY,
            mode: AddrMode::IZY,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 6,
        },
        Instruction {
            name: "STY",
            operate: CPU::STY,
            addr: CPU::ZPX,
            mode: AddrMode::ZPX,
            cycles: 4,
        },
        Instruction {
            name: "STA",
            operate: CPU::STA,
            addr: CPU::ZPX,
            mode: AddrMode::ZPX,
            cycles: 4,
        },
        Instruction {
            name: "STX",
            operate: CPU::STX,
            addr: CPU::ZPY,
            mode: AddrMode::ZPY,
            cycles: 4,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 4,
        },
        Instruction {
            name: "TYA",
            operate: CPU::TYA,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "STA",
            operate: CPU::STA,
            addr: CPU::ABY,
            mode: AddrMode::ABY,
            cycles: 5,
        },
        Instruction {
            name: "TXS",
            operate: CPU::TXS,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: CPU::NOP,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 5,
        },
        Instruction {
            name: "STA",
            operate: CPU::STA,
            addr: CPU::ABX,
            mode: AddrMode::ABX,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 5,
        },
    ],
    [
        Instruction {
            name: "LDY",
            operate: CPU::LDY,
            addr: CPU::IMM,
            mode: AddrMode::IMM,
            cycles: 2,
        },
        Instruction {
            name: "LDA",
            operate: CPU::LDA,
            addr: CPU::IZX,
            mode: AddrMode::IZX,
            cycles: 6,
        },
        Instruction {
            name: "LDX",
            operate: CPU::LDX,
            addr: CPU::IMM,
            mode: AddrMode::IMM,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 6,
        },
        Instruction {
            name: "LDY",
            operate: CPU::LDY,
            addr: CPU::ZP0,
            mode: AddrMode::ZP0,
            cycles: 3,
        },
        Instruction {
            name: "LDA",
            operate: CPU::LDA,
            addr: CPU::ZP0,
            mode: AddrMode::ZP0,
            cycles: 3,
        },
        Instruction {
            name: "LDX",
            operate: CPU::LDX,
            addr: CPU::ZP0,
            mode: AddrMode::ZP0,
            cycles: 3,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 3,
        },
        Instruction {
            name: "TAY",
            operate: CPU::TAY,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "LDA",
            operate: CPU::LDA,
            addr: CPU::IMM,
            mode: AddrMode::IMM,
            cycles: 2,
        },
        Instruction {
            name: "TAX",
            operate: CPU::TAX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "LDY",
            operate: CPU::LDY,
            addr: CPU::ABS,
            mode: AddrMode::ABS,
            cycles: 4,
        },
        Instruction {
            name: "LDA",
            operate: CPU::LDA,
            addr: CPU::ABS,
            mode: AddrMode::ABS,
            cycles: 4,
        },
        Instruction {
            name: "LDX",
            operate: CPU::LDX,
            addr: CPU::ABS,
            mode: AddrMode::ABS,
            cycles: 4,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 4,
        },
    ],
    [
        Instruction {
            name: "BCS",
            operate: CPU::BCS,
            addr: CPU::REL,
            mode: AddrMode::REL,
            cycles: 2,
        },
        Instruction {
            name: "LDA",
            operate: CPU::LDA,
            addr: CPU::IZY,
            mode: AddrMode::IZY,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 5,
        },
        Instruction {
            name: "LDY",
            operate: CPU::LDY,
            addr: CPU::ZPX,
            mode: AddrMode::ZPX,
            cycles: 4,
        },
        Instruction {
            name: "LDA",
            operate: CPU::LDA,
            addr: CPU::ZPX,
            mode: AddrMode::ZPX,
            cycles: 4,
        },
        Instruction {
            name: "LDX",
            operate: CPU::LDX,
            addr: CPU::ZPY,
            mode: AddrMode::ZPY,
            cycles: 4,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 4,
        },
        Instruction {
            name: "CLV",
            operate: CPU::CLV,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "LDA",
            operate: CPU::LDA,
            addr: CPU::ABY,
            mode: AddrMode::ABY,
            cycles: 4,
        },
        Instruction {
            name: "TSX",
            operate: CPU::TSX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 4,
        },
        Instruction {
            name: "LDY",
            operate: CPU::LDY,
            addr: CPU::ABX,
            mode: AddrMode::ABX,
            cycles: 4,
        },
        Instruction {
            name: "LDA",
            operate: CPU::LDA,
            addr: CPU::ABX,
            mode: AddrMode::ABX,
            cycles: 4,
        },
        Instruction {
            name: "LDX",
            operate: CPU::LDX,
            addr: CPU::ABY,
            mode: AddrMode::ABY,
            cycles: 4,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 4,
        },
    ],
    [
        Instruction {
            name: "CPY",
            operate: CPU::CPY,
            addr: CPU::IMM,
            mode: AddrMode::IMM,
            cycles: 2,
        },
        Instruction {
            name: "CMP",
            operate: CPU::CMP,
            addr: CPU::IZX,
            mode: AddrMode::IZX,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::NOP,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 8,
        },
        Instruction {
            name: "CPY",
            operate: CPU::CPY,
            addr: CPU::ZP0,
            mode: AddrMode::ZP0,
            cycles: 3,
        },
        Instruction {
            name: "CMP",
            operate: CPU::CMP,
            addr: CPU::ZP0,
            mode: AddrMode::ZP0,
            cycles: 3,
        },
        Instruction {
            name: "DEC",
            operate: CPU::DEC,
            addr: CPU::ZP0,
            mode: AddrMode::ZP0,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 5,
        },
        Instruction {
            name: "INY",
            operate: CPU::INY,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "CMP",
            operate: CPU::CMP,
            addr: CPU::IMM,
            mode: AddrMode::IMM,
            cycles: 2,
        },
        Instruction {
            name: "DEX",
            operate: CPU::DEX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "CPY",
            operate: CPU::CPY,
            addr: CPU::ABS,
            mode: AddrMode::ABS,
            cycles: 4,
        },
        Instruction {
            name: "CMP",
            operate: CPU::CMP,
            addr: CPU::ABS,
            mode: AddrMode::ABS,
            cycles: 4,
        },
        Instruction {
            name: "DEC",
            operate: CPU::DEC,
            addr: CPU::ABS,
            mode: AddrMode::ABS,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 6,
        },
    ],
    [
        Instruction {
            name: "BNE",
            operate: CPU::BNE,
            addr: CPU::REL,
            mode: AddrMode::REL,
            cycles: 2,
        },
        Instruction {
            name: "CMP",
            operate: CPU::CMP,
            addr: CPU::IZY,
            mode: AddrMode::IZY,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 8,
        },
        Instruction {
            name: "???",
            operate: CPU::NOP,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 4,
        },
        Instruction {
            name: "CMP",
            operate: CPU::CMP,
            addr: CPU::ZPX,
            mode: AddrMode::ZPX,
            cycles: 4,
        },
        Instruction {
            name: "DEC",
            operate: CPU::DEC,
            addr: CPU::ZPX,
            mode: AddrMode::ZPX,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 6,
        },
        Instruction {
            name: "CLD",
            operate: CPU::CLD,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "CMP",
            operate: CPU::CMP,
            addr: CPU::ABY,
            mode: AddrMode::ABY,
            cycles: 4,
        },
        Instruction {
            name: "NOP",
            operate: CPU::NOP,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: CPU::NOP,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 4,
        },
        Instruction {
            name: "CMP",
            operate: CPU::CMP,
            addr: CPU::ABX,
            mode: AddrMode::ABX,
            cycles: 4,
        },
        Instruction {
            name: "DEC",
            operate: CPU::DEC,
            addr: CPU::ABX,
            mode: AddrMode::ABX,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 7,
        },
    ],
    [
        Instruction {
            name: "CPX",
            operate: CPU::CPX,
            addr: CPU::IMM,
            mode: AddrMode::IMM,
            cycles: 2,
        },
        Instruction {
            name: "SBC",
            operate: CPU::SBC,
            addr: CPU::IZX,
            mode: AddrMode::IZX,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::NOP,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 8,
        },
        Instruction {
            name: "CPX",
            operate: CPU::CPX,
            addr: CPU::ZP0,
            mode: AddrMode::ZP0,
            cycles: 3,
        },
        Instruction {
            name: "SBC",
            operate: CPU::SBC,
            addr: CPU::ZP0,
            mode: AddrMode::ZP0,
            cycles: 3,
        },
        Instruction {
            name: "INC",
            operate: CPU::INC,
            addr: CPU::ZP0,
            mode: AddrMode::ZP0,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 5,
        },
        Instruction {
            name: "INX",
            operate: CPU::INX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "SBC",
            operate: CPU::SBC,
            addr: CPU::IMM,
            mode: AddrMode::IMM,
            cycles: 2,
        },
        Instruction {
            name: "NOP",
            operate: CPU::NOP,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::SBC,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "CPX",
            operate: CPU::CPX,
            addr: CPU::ABS,
            mode: AddrMode::ABS,
            cycles: 4,
        },
        Instruction {
            name: "SBC",
            operate: CPU::SBC,
            addr: CPU::ABS,
            mode: AddrMode::ABS,
            cycles: 4,
        },
        Instruction {
            name: "INC",
            operate: CPU::INC,
            addr: CPU::ABS,
            mode: AddrMode::ABS,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 6,
        },
    ],
    [
        Instruction {
            name: "BEQ",
            operate: CPU::BEQ,
            addr: CPU::REL,
            mode: AddrMode::REL,
            cycles: 2,
        },
        Instruction {
            name: "SBC",
            operate: CPU::SBC,
            addr: CPU::IZY,
            mode: AddrMode::IZY,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 8,
        },
        Instruction {
            name: "???",
            operate: CPU::NOP,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 4,
        },
        Instruction {
            name: "SBC",
            operate: CPU::SBC,
            addr: CPU::ZPX,
            mode: AddrMode::ZPX,
            cycles: 4,
        },
        Instruction {
            name: "INC",
            operate: CPU::INC,
            addr: CPU::ZPX,
            mode: AddrMode::ZPX,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 6,
        },
        Instruction {
            name: "SED",
            operate: CPU::SED,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "SBC",
            operate: CPU::SBC,
            addr: CPU::ABY,
            mode: AddrMode::ABY,
            cycles: 4,
        },
        Instruction {
            name: "NOP",
            operate: CPU::NOP,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: CPU::NOP,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 4,
        },
        Instruction {
            name: "SBC",
            operate: CPU::SBC,
            addr: CPU::ABX,
            mode: AddrMode::ABX,
            cycles: 4,
        },
        Instruction {
            name: "INC",
            operate: CPU::INC,
            addr: CPU::ABX,
            mode: AddrMode::ABX,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: CPU::XXX,
            addr: CPU::IMP,
            mode: AddrMode::IMP,
            cycles: 7,
        },
    ],
];
