use crate::bus::Bus;
use crate::cpu::CPU;

#[derive(Copy, Clone)]
pub struct Instruction {
    pub name: &'static str,
    pub addr: fn(&mut CPU, &mut Bus) -> u8,
    pub operate: fn(&mut CPU, &mut Bus) -> u8,
    pub mode: AddrMode,
    pub cycles: u8,
}

#[derive(Copy, Clone, PartialEq, Eq)]
pub enum AddrMode {
    Imp,
    Imm,
    Zp0,
    Zpx,
    Zpy,
    Rel,
    Abs,
    Abx,
    Aby,
    Ind,
    Izx,
    Izy,
}

pub fn get_instruction(opcode: u8) -> Instruction {
    let row = (opcode / 16) as usize;
    let col = (opcode % 16) as usize;

    INSTRUCTIONS[row][col]
}

const INSTRUCTIONS: [[Instruction; 16]; 16] = [
    [
        Instruction {
            name: "brk",
            operate: CPU::brk,
            addr: CPU::imm,
            mode: AddrMode::Imm,
            cycles: 7,
        },
        Instruction {
            name: "ora",
            operate: CPU::ora,
            addr: CPU::izx,
            mode: AddrMode::Izx,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 8,
        },
        Instruction {
            name: "???",
            operate: CPU::nop,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 3,
        },
        Instruction {
            name: "ora",
            operate: CPU::ora,
            addr: CPU::zp0,
            mode: AddrMode::Zp0,
            cycles: 3,
        },
        Instruction {
            name: "asl",
            operate: CPU::asl,
            addr: CPU::zp0,
            mode: AddrMode::Zp0,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 5,
        },
        Instruction {
            name: "php",
            operate: CPU::php,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 3,
        },
        Instruction {
            name: "ora",
            operate: CPU::ora,
            addr: CPU::imm,
            mode: AddrMode::Imm,
            cycles: 2,
        },
        Instruction {
            name: "asl",
            operate: CPU::asl,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::nop,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "ora",
            operate: CPU::ora,
            addr: CPU::abs,
            mode: AddrMode::Abs,
            cycles: 4,
        },
        Instruction {
            name: "asl",
            operate: CPU::asl,
            addr: CPU::abs,
            mode: AddrMode::Abs,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 6,
        },
    ],
    [
        Instruction {
            name: "bpl",
            operate: CPU::bpl,
            addr: CPU::rel,
            mode: AddrMode::Rel,
            cycles: 2,
        },
        Instruction {
            name: "ora",
            operate: CPU::ora,
            addr: CPU::izy,
            mode: AddrMode::Izy,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 8,
        },
        Instruction {
            name: "???",
            operate: CPU::nop,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "ora",
            operate: CPU::ora,
            addr: CPU::zpx,
            mode: AddrMode::Zpx,
            cycles: 4,
        },
        Instruction {
            name: "asl",
            operate: CPU::asl,
            addr: CPU::zpx,
            mode: AddrMode::Zpx,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 6,
        },
        Instruction {
            name: "clc",
            operate: CPU::clc,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "ora",
            operate: CPU::ora,
            addr: CPU::aby,
            mode: AddrMode::Aby,
            cycles: 4,
        },
        Instruction {
            name: "???",
            operate: CPU::nop,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: CPU::nop,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "ora",
            operate: CPU::ora,
            addr: CPU::abx,
            mode: AddrMode::Abx,
            cycles: 4,
        },
        Instruction {
            name: "asl",
            operate: CPU::asl,
            addr: CPU::abx,
            mode: AddrMode::Abx,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 7,
        },
    ],
    [
        Instruction {
            name: "jsr",
            operate: CPU::jsr,
            addr: CPU::abs,
            mode: AddrMode::Abs,
            cycles: 6,
        },
        Instruction {
            name: "and",
            operate: CPU::and,
            addr: CPU::izx,
            mode: AddrMode::Izx,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 8,
        },
        Instruction {
            name: "bit",
            operate: CPU::bit,
            addr: CPU::zp0,
            mode: AddrMode::Zp0,
            cycles: 3,
        },
        Instruction {
            name: "and",
            operate: CPU::and,
            addr: CPU::zp0,
            mode: AddrMode::Zp0,
            cycles: 3,
        },
        Instruction {
            name: "rol",
            operate: CPU::rol,
            addr: CPU::zp0,
            mode: AddrMode::Zp0,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 5,
        },
        Instruction {
            name: "plp",
            operate: CPU::plp,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "and",
            operate: CPU::and,
            addr: CPU::imm,
            mode: AddrMode::Imm,
            cycles: 2,
        },
        Instruction {
            name: "rol",
            operate: CPU::rol,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "bit",
            operate: CPU::bit,
            addr: CPU::abs,
            mode: AddrMode::Abs,
            cycles: 4,
        },
        Instruction {
            name: "and",
            operate: CPU::and,
            addr: CPU::abs,
            mode: AddrMode::Abs,
            cycles: 4,
        },
        Instruction {
            name: "rol",
            operate: CPU::rol,
            addr: CPU::abs,
            mode: AddrMode::Abs,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 6,
        },
    ],
    [
        Instruction {
            name: "bmi",
            operate: CPU::bmi,
            addr: CPU::rel,
            mode: AddrMode::Rel,
            cycles: 2,
        },
        Instruction {
            name: "and",
            operate: CPU::and,
            addr: CPU::izy,
            mode: AddrMode::Izy,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 8,
        },
        Instruction {
            name: "???",
            operate: CPU::nop,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "and",
            operate: CPU::and,
            addr: CPU::zpx,
            mode: AddrMode::Zpx,
            cycles: 4,
        },
        Instruction {
            name: "rol",
            operate: CPU::rol,
            addr: CPU::zpx,
            mode: AddrMode::Zpx,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 6,
        },
        Instruction {
            name: "sec",
            operate: CPU::sec,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "and",
            operate: CPU::and,
            addr: CPU::aby,
            mode: AddrMode::Aby,
            cycles: 4,
        },
        Instruction {
            name: "???",
            operate: CPU::nop,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: CPU::nop,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "and",
            operate: CPU::and,
            addr: CPU::abx,
            mode: AddrMode::Abx,
            cycles: 4,
        },
        Instruction {
            name: "rol",
            operate: CPU::rol,
            addr: CPU::abx,
            mode: AddrMode::Abx,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 7,
        },
    ],
    [
        Instruction {
            name: "rti",
            operate: CPU::rti,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 6,
        },
        Instruction {
            name: "eor",
            operate: CPU::eor,
            addr: CPU::izx,
            mode: AddrMode::Izx,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 8,
        },
        Instruction {
            name: "???",
            operate: CPU::nop,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 3,
        },
        Instruction {
            name: "eor",
            operate: CPU::eor,
            addr: CPU::zp0,
            mode: AddrMode::Zp0,
            cycles: 3,
        },
        Instruction {
            name: "lsr",
            operate: CPU::lsr,
            addr: CPU::zp0,
            mode: AddrMode::Zp0,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 5,
        },
        Instruction {
            name: "pha",
            operate: CPU::pha,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 3,
        },
        Instruction {
            name: "eor",
            operate: CPU::eor,
            addr: CPU::imm,
            mode: AddrMode::Imm,
            cycles: 2,
        },
        Instruction {
            name: "lsr",
            operate: CPU::lsr,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "jmp",
            operate: CPU::jmp,
            addr: CPU::abs,
            mode: AddrMode::Abs,
            cycles: 3,
        },
        Instruction {
            name: "eor",
            operate: CPU::eor,
            addr: CPU::abs,
            mode: AddrMode::Abs,
            cycles: 4,
        },
        Instruction {
            name: "lsr",
            operate: CPU::lsr,
            addr: CPU::abs,
            mode: AddrMode::Abs,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 6,
        },
    ],
    [
        Instruction {
            name: "bvc",
            operate: CPU::bvc,
            addr: CPU::rel,
            mode: AddrMode::Rel,
            cycles: 2,
        },
        Instruction {
            name: "eor",
            operate: CPU::eor,
            addr: CPU::izy,
            mode: AddrMode::Izy,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 8,
        },
        Instruction {
            name: "???",
            operate: CPU::nop,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "eor",
            operate: CPU::eor,
            addr: CPU::zpx,
            mode: AddrMode::Zpx,
            cycles: 4,
        },
        Instruction {
            name: "lsr",
            operate: CPU::lsr,
            addr: CPU::zpx,
            mode: AddrMode::Zpx,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 6,
        },
        Instruction {
            name: "cli",
            operate: CPU::cli,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "eor",
            operate: CPU::eor,
            addr: CPU::aby,
            mode: AddrMode::Aby,
            cycles: 4,
        },
        Instruction {
            name: "???",
            operate: CPU::nop,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: CPU::nop,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "eor",
            operate: CPU::eor,
            addr: CPU::abx,
            mode: AddrMode::Abx,
            cycles: 4,
        },
        Instruction {
            name: "lsr",
            operate: CPU::lsr,
            addr: CPU::abx,
            mode: AddrMode::Abx,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 7,
        },
    ],
    [
        Instruction {
            name: "rts",
            operate: CPU::rts,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 6,
        },
        Instruction {
            name: "adc",
            operate: CPU::adc,
            addr: CPU::izx,
            mode: AddrMode::Izx,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 8,
        },
        Instruction {
            name: "???",
            operate: CPU::nop,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 3,
        },
        Instruction {
            name: "adc",
            operate: CPU::adc,
            addr: CPU::zp0,
            mode: AddrMode::Zp0,
            cycles: 3,
        },
        Instruction {
            name: "ror",
            operate: CPU::ror,
            addr: CPU::zp0,
            mode: AddrMode::Zp0,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 5,
        },
        Instruction {
            name: "pla",
            operate: CPU::pla,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "adc",
            operate: CPU::adc,
            addr: CPU::imm,
            mode: AddrMode::Imm,
            cycles: 2,
        },
        Instruction {
            name: "ror",
            operate: CPU::ror,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "jmp",
            operate: CPU::jmp,
            addr: CPU::ind,
            mode: AddrMode::Ind,
            cycles: 5,
        },
        Instruction {
            name: "adc",
            operate: CPU::adc,
            addr: CPU::abs,
            mode: AddrMode::Abs,
            cycles: 4,
        },
        Instruction {
            name: "ror",
            operate: CPU::ror,
            addr: CPU::abs,
            mode: AddrMode::Abs,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 6,
        },
    ],
    [
        Instruction {
            name: "bvs",
            operate: CPU::bvs,
            addr: CPU::rel,
            mode: AddrMode::Rel,
            cycles: 2,
        },
        Instruction {
            name: "adc",
            operate: CPU::adc,
            addr: CPU::izy,
            mode: AddrMode::Izy,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 8,
        },
        Instruction {
            name: "???",
            operate: CPU::nop,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "adc",
            operate: CPU::adc,
            addr: CPU::zpx,
            mode: AddrMode::Zpx,
            cycles: 4,
        },
        Instruction {
            name: "ror",
            operate: CPU::ror,
            addr: CPU::zpx,
            mode: AddrMode::Zpx,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 6,
        },
        Instruction {
            name: "sei",
            operate: CPU::sei,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "adc",
            operate: CPU::adc,
            addr: CPU::aby,
            mode: AddrMode::Aby,
            cycles: 4,
        },
        Instruction {
            name: "???",
            operate: CPU::nop,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: CPU::nop,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "adc",
            operate: CPU::adc,
            addr: CPU::abx,
            mode: AddrMode::Abx,
            cycles: 4,
        },
        Instruction {
            name: "ror",
            operate: CPU::ror,
            addr: CPU::abx,
            mode: AddrMode::Abx,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 7,
        },
    ],
    [
        Instruction {
            name: "???",
            operate: CPU::nop,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "sta",
            operate: CPU::sta,
            addr: CPU::izx,
            mode: AddrMode::Izx,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::nop,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 6,
        },
        Instruction {
            name: "sty",
            operate: CPU::sty,
            addr: CPU::zp0,
            mode: AddrMode::Zp0,
            cycles: 3,
        },
        Instruction {
            name: "sta",
            operate: CPU::sta,
            addr: CPU::zp0,
            mode: AddrMode::Zp0,
            cycles: 3,
        },
        Instruction {
            name: "stx",
            operate: CPU::stx,
            addr: CPU::zp0,
            mode: AddrMode::Zp0,
            cycles: 3,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 3,
        },
        Instruction {
            name: "dey",
            operate: CPU::dey,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::nop,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "txa",
            operate: CPU::txa,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "sty",
            operate: CPU::sty,
            addr: CPU::abs,
            mode: AddrMode::Abs,
            cycles: 4,
        },
        Instruction {
            name: "sta",
            operate: CPU::sta,
            addr: CPU::abs,
            mode: AddrMode::Abs,
            cycles: 4,
        },
        Instruction {
            name: "stx",
            operate: CPU::stx,
            addr: CPU::abs,
            mode: AddrMode::Abs,
            cycles: 4,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
    ],
    [
        Instruction {
            name: "bcc",
            operate: CPU::bcc,
            addr: CPU::rel,
            mode: AddrMode::Rel,
            cycles: 2,
        },
        Instruction {
            name: "sta",
            operate: CPU::sta,
            addr: CPU::izy,
            mode: AddrMode::Izy,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 6,
        },
        Instruction {
            name: "sty",
            operate: CPU::sty,
            addr: CPU::zpx,
            mode: AddrMode::Zpx,
            cycles: 4,
        },
        Instruction {
            name: "sta",
            operate: CPU::sta,
            addr: CPU::zpx,
            mode: AddrMode::Zpx,
            cycles: 4,
        },
        Instruction {
            name: "stx",
            operate: CPU::stx,
            addr: CPU::zpy,
            mode: AddrMode::Zpy,
            cycles: 4,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "tya",
            operate: CPU::tya,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "sta",
            operate: CPU::sta,
            addr: CPU::aby,
            mode: AddrMode::Aby,
            cycles: 5,
        },
        Instruction {
            name: "txs",
            operate: CPU::txs,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: CPU::nop,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 5,
        },
        Instruction {
            name: "sta",
            operate: CPU::sta,
            addr: CPU::abx,
            mode: AddrMode::Abx,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 5,
        },
    ],
    [
        Instruction {
            name: "ldy",
            operate: CPU::ldy,
            addr: CPU::imm,
            mode: AddrMode::Imm,
            cycles: 2,
        },
        Instruction {
            name: "lda",
            operate: CPU::lda,
            addr: CPU::izx,
            mode: AddrMode::Izx,
            cycles: 6,
        },
        Instruction {
            name: "ldx",
            operate: CPU::ldx,
            addr: CPU::imm,
            mode: AddrMode::Imm,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 6,
        },
        Instruction {
            name: "ldy",
            operate: CPU::ldy,
            addr: CPU::zp0,
            mode: AddrMode::Zp0,
            cycles: 3,
        },
        Instruction {
            name: "lda",
            operate: CPU::lda,
            addr: CPU::zp0,
            mode: AddrMode::Zp0,
            cycles: 3,
        },
        Instruction {
            name: "ldx",
            operate: CPU::ldx,
            addr: CPU::zp0,
            mode: AddrMode::Zp0,
            cycles: 3,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 3,
        },
        Instruction {
            name: "tay",
            operate: CPU::tay,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "lda",
            operate: CPU::lda,
            addr: CPU::imm,
            mode: AddrMode::Imm,
            cycles: 2,
        },
        Instruction {
            name: "tax",
            operate: CPU::tax,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "ldy",
            operate: CPU::ldy,
            addr: CPU::abs,
            mode: AddrMode::Abs,
            cycles: 4,
        },
        Instruction {
            name: "lda",
            operate: CPU::lda,
            addr: CPU::abs,
            mode: AddrMode::Abs,
            cycles: 4,
        },
        Instruction {
            name: "ldx",
            operate: CPU::ldx,
            addr: CPU::abs,
            mode: AddrMode::Abs,
            cycles: 4,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
    ],
    [
        Instruction {
            name: "bcs",
            operate: CPU::bcs,
            addr: CPU::rel,
            mode: AddrMode::Rel,
            cycles: 2,
        },
        Instruction {
            name: "lda",
            operate: CPU::lda,
            addr: CPU::izy,
            mode: AddrMode::Izy,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 5,
        },
        Instruction {
            name: "ldy",
            operate: CPU::ldy,
            addr: CPU::zpx,
            mode: AddrMode::Zpx,
            cycles: 4,
        },
        Instruction {
            name: "lda",
            operate: CPU::lda,
            addr: CPU::zpx,
            mode: AddrMode::Zpx,
            cycles: 4,
        },
        Instruction {
            name: "ldx",
            operate: CPU::ldx,
            addr: CPU::zpy,
            mode: AddrMode::Zpy,
            cycles: 4,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "clv",
            operate: CPU::clv,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "lda",
            operate: CPU::lda,
            addr: CPU::aby,
            mode: AddrMode::Aby,
            cycles: 4,
        },
        Instruction {
            name: "tsx",
            operate: CPU::tsx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "ldy",
            operate: CPU::ldy,
            addr: CPU::abx,
            mode: AddrMode::Abx,
            cycles: 4,
        },
        Instruction {
            name: "lda",
            operate: CPU::lda,
            addr: CPU::abx,
            mode: AddrMode::Abx,
            cycles: 4,
        },
        Instruction {
            name: "ldx",
            operate: CPU::ldx,
            addr: CPU::aby,
            mode: AddrMode::Aby,
            cycles: 4,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
    ],
    [
        Instruction {
            name: "cpy",
            operate: CPU::cpy,
            addr: CPU::imm,
            mode: AddrMode::Imm,
            cycles: 2,
        },
        Instruction {
            name: "cmp",
            operate: CPU::cmp,
            addr: CPU::izx,
            mode: AddrMode::Izx,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::nop,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 8,
        },
        Instruction {
            name: "cpy",
            operate: CPU::cpy,
            addr: CPU::zp0,
            mode: AddrMode::Zp0,
            cycles: 3,
        },
        Instruction {
            name: "cmp",
            operate: CPU::cmp,
            addr: CPU::zp0,
            mode: AddrMode::Zp0,
            cycles: 3,
        },
        Instruction {
            name: "dec",
            operate: CPU::dec,
            addr: CPU::zp0,
            mode: AddrMode::Zp0,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 5,
        },
        Instruction {
            name: "iny",
            operate: CPU::iny,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "cmp",
            operate: CPU::cmp,
            addr: CPU::imm,
            mode: AddrMode::Imm,
            cycles: 2,
        },
        Instruction {
            name: "dex",
            operate: CPU::dex,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "cpy",
            operate: CPU::cpy,
            addr: CPU::abs,
            mode: AddrMode::Abs,
            cycles: 4,
        },
        Instruction {
            name: "cmp",
            operate: CPU::cmp,
            addr: CPU::abs,
            mode: AddrMode::Abs,
            cycles: 4,
        },
        Instruction {
            name: "dec",
            operate: CPU::dec,
            addr: CPU::abs,
            mode: AddrMode::Abs,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 6,
        },
    ],
    [
        Instruction {
            name: "bne",
            operate: CPU::bne,
            addr: CPU::rel,
            mode: AddrMode::Rel,
            cycles: 2,
        },
        Instruction {
            name: "cmp",
            operate: CPU::cmp,
            addr: CPU::izy,
            mode: AddrMode::Izy,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 8,
        },
        Instruction {
            name: "???",
            operate: CPU::nop,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "cmp",
            operate: CPU::cmp,
            addr: CPU::zpx,
            mode: AddrMode::Zpx,
            cycles: 4,
        },
        Instruction {
            name: "dec",
            operate: CPU::dec,
            addr: CPU::zpx,
            mode: AddrMode::Zpx,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 6,
        },
        Instruction {
            name: "cld",
            operate: CPU::cld,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "cmp",
            operate: CPU::cmp,
            addr: CPU::aby,
            mode: AddrMode::Aby,
            cycles: 4,
        },
        Instruction {
            name: "nop",
            operate: CPU::nop,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: CPU::nop,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "cmp",
            operate: CPU::cmp,
            addr: CPU::abx,
            mode: AddrMode::Abx,
            cycles: 4,
        },
        Instruction {
            name: "dec",
            operate: CPU::dec,
            addr: CPU::abx,
            mode: AddrMode::Abx,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 7,
        },
    ],
    [
        Instruction {
            name: "cpx",
            operate: CPU::cpx,
            addr: CPU::imm,
            mode: AddrMode::Imm,
            cycles: 2,
        },
        Instruction {
            name: "sbc",
            operate: CPU::sbc,
            addr: CPU::izx,
            mode: AddrMode::Izx,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::nop,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 8,
        },
        Instruction {
            name: "cpx",
            operate: CPU::cpx,
            addr: CPU::zp0,
            mode: AddrMode::Zp0,
            cycles: 3,
        },
        Instruction {
            name: "sbc",
            operate: CPU::sbc,
            addr: CPU::zp0,
            mode: AddrMode::Zp0,
            cycles: 3,
        },
        Instruction {
            name: "inc",
            operate: CPU::inc,
            addr: CPU::zp0,
            mode: AddrMode::Zp0,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 5,
        },
        Instruction {
            name: "inx",
            operate: CPU::inx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "sbc",
            operate: CPU::sbc,
            addr: CPU::imm,
            mode: AddrMode::Imm,
            cycles: 2,
        },
        Instruction {
            name: "nop",
            operate: CPU::nop,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::sbc,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "cpx",
            operate: CPU::cpx,
            addr: CPU::abs,
            mode: AddrMode::Abs,
            cycles: 4,
        },
        Instruction {
            name: "sbc",
            operate: CPU::sbc,
            addr: CPU::abs,
            mode: AddrMode::Abs,
            cycles: 4,
        },
        Instruction {
            name: "inc",
            operate: CPU::inc,
            addr: CPU::abs,
            mode: AddrMode::Abs,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 6,
        },
    ],
    [
        Instruction {
            name: "beq",
            operate: CPU::beq,
            addr: CPU::rel,
            mode: AddrMode::Rel,
            cycles: 2,
        },
        Instruction {
            name: "sbc",
            operate: CPU::sbc,
            addr: CPU::izy,
            mode: AddrMode::Izy,
            cycles: 5,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 8,
        },
        Instruction {
            name: "???",
            operate: CPU::nop,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "sbc",
            operate: CPU::sbc,
            addr: CPU::zpx,
            mode: AddrMode::Zpx,
            cycles: 4,
        },
        Instruction {
            name: "inc",
            operate: CPU::inc,
            addr: CPU::zpx,
            mode: AddrMode::Zpx,
            cycles: 6,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 6,
        },
        Instruction {
            name: "sed",
            operate: CPU::sed,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "sbc",
            operate: CPU::sbc,
            addr: CPU::aby,
            mode: AddrMode::Aby,
            cycles: 4,
        },
        Instruction {
            name: "nop",
            operate: CPU::nop,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 2,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: CPU::nop,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 4,
        },
        Instruction {
            name: "sbc",
            operate: CPU::sbc,
            addr: CPU::abx,
            mode: AddrMode::Abx,
            cycles: 4,
        },
        Instruction {
            name: "inc",
            operate: CPU::inc,
            addr: CPU::abx,
            mode: AddrMode::Abx,
            cycles: 7,
        },
        Instruction {
            name: "???",
            operate: CPU::xxx,
            addr: CPU::imp,
            mode: AddrMode::Imp,
            cycles: 7,
        },
    ],
];
